-- 코드를 입력하세요
SELECT M.MEMBER_ID, M.MEMBER_NAME, M.GENDER, DATE_FORMAT(M.DATE_OF_BIRTH, "%Y-%m-%d") DATE_OF_BIRTH
FROM MEMBER_PROFILE M
WHERE M.TLNO IS NOT NULL
AND M.GENDER = 'W'
AND DATE_FORMAT(M.DATE_OF_BIRTH,'%m') = 3
ORDER BY M.MEMBER_ID ASC
