WITH T AS (
    SELECT COUNT(DISTINCT USER_ID) CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) 
SELECT YEAR(O.SALES_DATE) YEAR, 
        MONTH(O.SALES_DATE) MONTH, 
        COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS, 
        ROUND(COUNT(DISTINCT O.USER_ID)/T.CNT ,1)PUCHASED_RATIO
FROM USER_INFO U INNER JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
                JOIN T 
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH

/*
다른풀이

SELECT YEAR(O.SALES_DATE) AS YEAR, 
        MONTH(O.SALES_DATE) AS MONTH, 
        COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS, 
        ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) 
                                            FROM USER_INFO 
                                            WHERE joined < '2022-01-01 00:00:00'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS O
JOIN USER_INFO AS U
ON O.USER_ID = U.USER_ID
WHERE joined < '2022-01-01 00:00:00'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH


*/
