-- 코드를 입력하세요
SELECT P.CATEGORY, P.PRICE , P.PRODUCT_NAME
FROM FOOD_PRODUCT P LEFT JOIN FOOD_PRODUCT F
        ON (P.CATEGORY = F.CATEGORY AND P.PRICE < F.PRICE)
WHERE F.PRICE IS NULL AND P.CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY P.CATEGORY
ORDER BY P.PRICE DESC


/*

SELECT A.CATEGORY , A.PRICE , B.PRODUCT_NAME 
FROM (
        SELECT 
                 CATEGORY, MAX(PRICE) PRICE
        FROM FOOD_PRODUCT
        WHERE CATEGORY IN ('과자','국','김치','식용유')
        GROUP BY CATEGORY
) A
INNER JOIN FOOD_PRODUCT B ON A.CATEGORY =B.CATEGORY AND A.PRICE = B.PRICE
ORDER BY A.PRICE DESC
*/
