-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID, 
    DATE_FORMAT(START_DATE, "%Y-%m-%d") START_DATE , 
    DATE_FORMAT(END_DATE, "%Y-%m-%d") END_DATE,
    case when (DATEDIFF(END_DATE, START_DATE)+1) >= 30 THEN '장기 대여'
    else '단기 대여' end as 'RENT_TYPE'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, "%Y%m") = '202209'
order by HISTORY_ID DESC
