SELECT B.HISTORY_ID, IF(DUR_TYPE IS NULL, 
                        B.durdur*A.DAILY_FEE,
                       ROUND(B.durdur*A.DAILY_FEE*(1-C.DISCOUNT_RATE/100))) FEE
FROM (SELECT HISTORY_ID, CAR_ID, CASE
            WHEN DATEDIFF(END_DATE ,START_DATE)+1 < 7 THEN 0
            WHEN DATEDIFF(END_DATE ,START_DATE)+1 BETWEEN 7 AND 29 THEN 7
            WHEN DATEDIFF(END_DATE ,START_DATE)+1 BETWEEN 30 AND 89 THEN 30
            ELSE 90 END AS CAT_DATE, START_DATE,END_DATE,
            DATEDIFF(END_DATE ,START_DATE)+1 AS durdur
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) B
    INNER JOIN (
        SELECT *
        FROM CAR_RENTAL_COMPANY_CAR
        ) AS A ON (A.CAR_ID = B.CAR_ID)
    LEFT JOIN (
        SELECT *, ROUND(REPLACE(DURATION_TYPE,'일 이상' , '')) DUR_TYPE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    ) AS C ON (C.DUR_TYPE = B.CAT_DATE AND C.CAR_TYPE = A.CAR_TYPE)
WHERE A.CAR_TYPE ='트럭'
ORDER BY FEE DESC, B.HISTORY_ID DESC
