-- 코드를 입력하세요
-- SELECT DATE_FORMAT("2021/01/24 12:33:32", "%Y-%m-%d");
SELECT B.BOOK_ID, DATE_FORMAT(B.PUBLISHED_DATE, "%Y-%m-%d")
FROM BOOK B
WHERE B.CATEGORY = '인문' and DATE_FORMAT(B.PUBLISHED_DATE, "%Y") = '2021'
ORDER BY B.PUBLISHED_DATE ASC
