SELECT U.BOARD_ID, U.WRITER_ID, U.TITLE, U.PRICE, IF(U.STATUS = 'SALE', '판매중',IF (U.STATUS = 'DONE', '거래완료','예약중')) AS 'STATUS'
FROM USED_GOODS_BOARD U
WHERE U.CREATED_DATE = '2022-10-05'
ORDER BY U.BOARD_ID DESC
