-- 코드를 입력하세요
WITH TOTAL_TABLE AS (
SELECT F.FLAVOR, SUM(F.TOTAL_ORDER) TOTAL FROM FIRST_HALF F
GROUP BY F.FLAVOR
UNION ALL
SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) TOTAL FROM JULY J
GROUP BY J.FLAVOR)

SELECT FLAVOR
FROM TOTAL_TABLE
GROUP BY FLAVOR
ORDER BY SUM(TOTAL) DESC
LIMIT 3


/*
다른 풀이들

SELECT FLAVOR
FROM
    (
        SELECT *
        FROM JULY
        UNION ALL
        SELECT *
        FROM FIRST_HALF
    ) A
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3

SELECT ju.FLAVOR
FROM JULY ju
JOIN FIRST_HALF fi ON ju.flavor = fi.flavor
GROUP BY ju.flavor
ORDER BY SUM(ju.total_order)+fi.total_order DESC
LIMIT 3

*/
