WITH T AS (
    SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
    FROM REST_INFO R
    GROUP BY R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
    ORDER BY R.FAVORITES DESC
)
SELECT * FROM T
GROUP BY T.FOOD_TYPE
ORDER BY T.FOOD_TYPE DESC


/*

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
    FROM REST_INFO A
        LEFT JOIN REST_INFO B ON A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES < B.FAVORITES
    WHERE B.FOOD_TYPE IS NULL
    ORDER BY A.FOOD_TYPE DESC;

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;

*/
