-- 코드를 입력하세요
SELECT B.CATEGORY , SUM(BS.SALES) TOTAL_SALES
FROM BOOK_SALES BS JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE)=1
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY
