-- 코드를 입력하세요
SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P INNER JOIN (
    SELECT HOST_ID, COUNT(HOST_ID) CNT
    FROM PLACES
    GROUP BY HOST_ID
    HAVING CNT > 1) K ON P.HOST_ID = K.HOST_ID
ORDER BY P.ID
